[package]
name = "evernote_rs_sdk_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrift-parser = "0.0.5"
clap = "~2.33.0"
